# Generated by Django 4.2.7 on 2023-11-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answer_rating_alter_question_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
